-- 상품을 코드가 아니라 DB에서 관리하기 위한 테이블 + 상품 사진 업로드용 Storage 버킷.
-- Supabase 대시보드 → SQL Editor 에서 이 파일 내용을 그대로 실행하세요. 여러 번 실행해도 안전합니다.

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  name_en text not null,
  name_mn text not null,
  category text not null,
  category_en text not null,
  category_mn text not null,
  type text not null,
  price integer not null,
  sale_price integer,
  badge text,
  image text,
  emoji text,
  swatches jsonb not null default '[]'::jsonb,
  sizes jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;

-- 상품 목록은 누구나(로그인 안 해도) 볼 수 있음
drop policy if exists "Anyone can view products" on public.products;
create policy "Anyone can view products"
  on public.products for select
  to anon, authenticated
  using (true);

-- 등록/수정/삭제는 관리자 계정만 가능
drop policy if exists "Admin can insert products" on public.products;
create policy "Admin can insert products"
  on public.products for insert
  to authenticated
  with check (auth.jwt() ->> 'email' = 'mandahnar15@gmail.com');

drop policy if exists "Admin can update products" on public.products;
create policy "Admin can update products"
  on public.products for update
  to authenticated
  using (auth.jwt() ->> 'email' = 'mandahnar15@gmail.com')
  with check (auth.jwt() ->> 'email' = 'mandahnar15@gmail.com');

drop policy if exists "Admin can delete products" on public.products;
create policy "Admin can delete products"
  on public.products for delete
  to authenticated
  using (auth.jwt() ->> 'email' = 'mandahnar15@gmail.com');

-- 기존에 코드에 하드코딩돼 있던 상품 8개를 그대로 이관 (id를 유지해서 기존 장바구니/찜/URL이 깨지지 않도록 함)
insert into public.products (id, name, name_en, name_mn, category, category_en, category_mn, type, price, sale_price, badge, image, emoji, swatches, sizes) values
(1, '오버사이즈 후드티', 'Oversized Hoodie', 'Оверсайз худи', '아우터', 'Outerwear', 'Гадуур хувцас', 'hoodies', 85000, 68000, 'SALE', '/products/hoodie.jpg', '🧥', '["#111111","#f5f5f5","#707072"]', '["Free"]'),
(2, '와이드 데님 팬츠', 'Wide-Leg Jeans', 'Өргөн жийнс', '데님', 'Denim', 'Жийнс', 'pantsdenim', 79000, null, null, '/products/denim.jpg', '👖', '["#111111","#4b4b4d"]', '["S","M","L"]'),
(3, '오프숄더 스트라이프 니트탑', 'Off-Shoulder Striped Knit Top', 'Нэг мөртэй судалтай сүлжмэл топ', '니트', 'Knitwear', 'Сүлжмэл', 'knitwears', 45000, null, 'NEW', '/products/knit-top.jpg', '🎽', '["#111111","#ed1aa0","#f5f5f5"]', '["S","M","L"]'),
(4, '체크 미디 스커트', 'Check Midi Skirt', 'Нүдэн хээтэй миди юбка', '스커트', 'Skirts', 'Юбка', 'dressskirts', 59000, null, null, '/products/check-skirt.jpg', '👗', '["#111111","#707072"]', '["S","M","L"]'),
(5, '오버사이즈 워커 재킷', 'Oversized Worker Jacket', 'Оверсайз ажлын куртка', '아우터', 'Outerwear', 'Гадуур хувцас', 'jackets', 129000, 99000, 'SALE', '/products/worker-jacket.jpg', '🧥', '["#111111","#f5f5f5"]', '["Free"]'),
(6, '오프숄더 크롭탑', 'Off-Shoulder Crop Top', 'Нэг мөртэй богино топ', '상의', 'Tops', 'Дээд хувцас', 'tops', 89000, null, 'NEW', '/products/offshoulder-top.jpg', '👚', '["#111111","#ed1aa0"]', '["S","M","L"]'),
(7, '타이다이 그래픽 롱슬리브', 'Tie-Dye Graphic Long Sleeve', 'Тай-дай хэвлэлттэй урт ханцуйтай цамц', '상의', 'Tops', 'Дээд хувцас', 'longsleeve', 32000, null, null, '/products/tiedye-longsleeve.jpg', '👕', '["#111111","#f5f5f5","#9e9ea0"]', '["S","M","L"]'),
(8, '레이스업 스니커즈', 'Lace-Up Sneakers', 'Оосорт сникерс', '신발', 'Shoes', 'Гутал', 'other', 89000, null, null, '/products/sneakers.jpg', '👟', '["#111111","#707072"]', '["230","235","240","245","250","255","260"]')
on conflict (id) do nothing;

-- 다음에 등록되는 상품의 id가 9부터 이어지도록 시퀀스를 맞춰줌
select setval(pg_get_serial_sequence('public.products', 'id'), (select max(id) from public.products));

-- 상품 사진을 관리자 페이지에서 업로드할 수 있도록 Storage 버킷 생성
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

drop policy if exists "Anyone can view product images" on storage.objects;
create policy "Anyone can view product images"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'product-images');

drop policy if exists "Admin can upload product images" on storage.objects;
create policy "Admin can upload product images"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'product-images' and auth.jwt() ->> 'email' = 'mandahnar15@gmail.com');

drop policy if exists "Admin can update product images" on storage.objects;
create policy "Admin can update product images"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'product-images' and auth.jwt() ->> 'email' = 'mandahnar15@gmail.com');

drop policy if exists "Admin can delete product images" on storage.objects;
create policy "Admin can delete product images"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'product-images' and auth.jwt() ->> 'email' = 'mandahnar15@gmail.com');
